#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "DataAdapterAlarmHostsProtocol.h"
#import "DSSAlarmHostsInfo.h"
#import "DataAdapterAlarmSchemeProtocol.h"
#import "DSSAlarmSchemeInfo.h"
#import "DataAdapterCallProtocol.h"
#import "DSSCallInfo.h"
#import "DSSCallVTInfo.h"
#import "DataAdapterCoreProtocol.h"
#import "DHThreadSafeMultableArray.h"
#import "DHThreadSafeMultableDictionary.h"
#import "DSSBaseInfo.h"
#import "WeikitErrorCode.h"
#import "DHModuleEventDefine.h"
#import "DHSubSystemDefine.h"
#import "RemoteNotifyDefine.h"
#import "DataAdapterDeviceProtocol.h"
#import "DataAdapterICCMapProtocol.h"
#import "DSSChannelInfo.h"
#import "DSSDeviceInfo.h"
#import "DSSDeviceInfo_DeviceRight.h"
#import "DSSEMapUIDataModel.h"
#import "DSSGroupInfo+FinanceInfo.h"
#import "DSSGroupInfo.h"
#import "DSSGroupInfo_GroupRight.h"
#import "DSSLocationConverter.h"
#import "DSSMapLayer.h"
#import "DSSMediaVKInfo.h"
#import "DSSUnitInfo.h"
#import "DSSUserViewInfo.h"
#import "DataAdapterBluetoochEntranceGuardProtocol.h"
#import "DataAdapterEntranceGuardProtocol.h"
#import "DSSBluetoochBindInfo.h"
#import "DSSDoorHistoryInfo.h"
#import "DSSGuardDoorStatus.h"
#import "DSSGuardPersonDepartmentInfo.h"
#import "DSSGuardPersonGroupInfo.h"
#import "DSSGuardPersonInfo.h"
#import "GuardDoorComand.h"
#import "DataAdapterFaceRecognitionProtocol.h"
#import "DSSFaceRecognitionInfo.h"
#import "DSSFaceStatisticsInfo.h"
#import "DataAdapterFavouriteProtocol.h"
#import "DataAdapterFavProtocol.h"
#import "DataAdapterHistoryProtocol.h"
#import "DataAdapterSearchHistoryProtocol.h"
#import "DataAdapterSearchModelProtocol.h"
#import "DSSHistoryInfo.h"
#import "DSSHistoryInfoGroup.h"
#import "AlarmMessageType.h"
#import "DataAdapterGMCommonMessageProtocol.h"
#import "DataAdapterMessageInfoTaskProtocol.h"
#import "DataAdapterMessageProtocol.h"
#import "DSSAlarmCapabilityInfo.h"
#import "DSSMessageCountInfo.h"
#import "DSSMessageFilterInfo.h"
#import "DSSMessageInfo.h"
#import "DSSMessageNotificationInfo.h"
#import "DSSMessageTaskInfo.h"
#import "DSSMessageTaskTypeInfo.h"
#import "DataAdapterModuleManageProtocol.h"
#import "DSSModuleInfo.h"
#import "DataAdapterObjectDetectionProtocol.h"
#import "DSSObjectDetectionInfo.h"
#import "DataAdapterPassengerFlowProtocol.h"
#import "DSSPassengerFlowDataInfo.h"
#import "DataAdapterPatrolProtocol.h"
#import "DSSPatrolInfo.h"
#import "DataAdapterPersonnelManagementProtocol.h"
#import "DSSPersonnelManagementInfo.h"
#import "DataAdapterRecordProtocol.h"
#import "DSSRecordInfo.h"
#import "DataAdapterRemoteNotifyProtocol.h"
#import "RemoteNotifyModuleServiceProtocol.h"
#import "DataAdapterSignalProtocol.h"
#import "DSSSignalInfo.h"
#import "DSSSpecialTaskInfo.h"
#import "DataAdapterTVWallProtocol.h"
#import "TVWallInfo.h"
#import "DataAdapterUserDetailProtocol.h"
#import "DSSAppConfigInfo.h"
#import "DSSMajorMenuInfo.h"
#import "DSSUserInfo.h"
#import "UserAdapterUserProtocol.h"
#import "DataAdapterVideoIntercomRecordProtocol.h"
#import "DSSVideoIntercomRecordInfo.h"
#import "DataAdapterVideoPlayProtocol.h"
#import "DSSVideoUrlInfo.h"
#import "DataAdapterVideoShareProtocol.h"
#import "DSSVideoShareChannelInfo.h"
#import "DSSVideoShareDeptInfo.h"
#import "DSSVideoShareResultInfo.h"
#import "DSSVideoShareShareInfo.h"
#import "DSSVideoShareUserInfo.h"
#import "DataAdapterVisitorProtocol.h"
#import "DSSVTSSVisitorAuthInfo.h"
#import "DSSVTSSVisitorConfigInfo.h"
#import "DSSVTSSVisitorInfo.h"
#import "DataAdapterVTSSProtocol.h"
#import "DSSVTSSACRecordInfo.h"
#import "DSSVTSSCallRecordInfo.h"
#import "DSSVTSSUserGroupInfo.h"
#import "DataAdapterWisdomElecProtocol.h"
#import "DSSWisdomElecAlertNode.h"
#import "DSSWisdomElecDetailNode.h"
#import "DSSWisdomElecListNode.h"

FOUNDATION_EXPORT double ICCDataAdapterProtocolVersionNumber;
FOUNDATION_EXPORT const unsigned char ICCDataAdapterProtocolVersionString[];

