//
//  RemoteNotifyModuleServiceProtocol.h
//  Pods
//
//  Created by zyx on 17/2/22.
//
//

#import <Foundation/Foundation.h>
#import "DataAdapterRemoteNotifyProtocol.h"

typedef enum _REMOTE_NOTIFY_ACTION : NSUInteger {
    REMOTE_NOTIFY_ACTION_UNKNOW,
    REMOTE_NOTIFY_ACTION_SERVER_DISCONNECT,    ///<server disconnect
    REMOTE_NOTIFY_ACTION_SERVER_CONNECTING,    ///<server connecting
    REMOTE_NOTIFY_ACTION_SERVER_CONNECTED,      ///<server connected
    REMOTE_NOTIFY_ACTION_SERVER_RECONNECTED,
    REMOTE_NOTIFY_ACTION_SERVER_TOKEN_CHANGED,
    REMOTE_NOTIFY_ACTION_SERVER_LOGOUT,       ///<logout
    REMOTE_NOTIFY_ACTION_SWITCH_CENTER_STATUS,
    
     REMOTE_NOTIFY_ACTION_DEVICE_LOAD_GROUP,
    REMOTE_NOTIFY_ACTION_DEVICE_LOAD_DEVICE, ///<DeviceInfo
    REMOTE_NOTIFY_ACTION_DEVICE_LOAD_UNIT, ///<UnitInfo
    REMOTE_NOTIFY_ACTION_DEVICE_LOAD_CHANNEL,    ///<ChannelInfo
    
    REMOTE_NOTIFY_ACTION_DEVICE_ADD_GROUP,  ///<GroupInfo
    REMOTE_NOTIFY_ACTION_DEVICE_SET_ROOT_GROUPID, ///<NSString，组织树的根节点
    REMOTE_NOTIFY_ACTION_DEVICE_SET_BASIC_ROOT_GROUPID,  ///<NSString，基本组织树的根节点
    REMOTE_NOTIFY_ACTION_DEVICE_ADD_DEVICE, ///<DeviceInfo
    REMOTE_NOTIFY_ACTION_DEVICE_ADD_UNIT, ///<UnitInfo
    REMOTE_NOTIFY_ACTION_DEVICE_ADD_CHANNEL,    ///<ChannelInfo
    REMOTE_NOTIFY_ACTION_DEVICE_STATUS,     ///<DeviceInfo在线离线
    REMOTE_NOTIFY_ACTION_CHANNEL_STATUS,     ///<通道状态通知-在线离线
    
    REMOTE_NOTIFY_ACTION_ALARMHOST_DEVICE_STATUS,   ///<设备布撤防状态更新-DeviceInfo
    REMOTE_NOTIFY_ACTION_ALARMHOST_UNIT_STATUS,     ///<单元/子防区/子防区 状态更新-UnitInfo
    REMOTE_NOTIFY_ACTION_ALARMHOST_CHANNEL_STATUS,  ///<通道 旁路、取消旁路、报警状态更新-ChannelInfo
    
    REMOTE_NOTIFY_ACTION_ALARMSCHEME_ADD,   ///<add AlarmSchemeInfo
    REMOTE_NOTIFY_ACTION_ALARMSCHEME_DELETE,   ///<delete AlarmSchemeInfo
    REMOTE_NOTIFY_ACTION_ALARMSCHEME_UPDATE,   ///<update AlarmSchemeInfo
    REMOTE_NOTIFY_ACTION_ADS_CONNECTED,        ///<ads连接成功
    
    REMOTE_NOTIFY_ACTION_MESSAGE_GPS,       ///<GPS设备信息上报
    REMOTE_NOTIFY_ACTION_MQ_GPS,       ///<GPS设备信息上报MQ
    REMOTE_NOTIFY_ACTION_MQ_REPORTGPSINFO,

    REMOTE_NOTIFY_ACTION_MAP_ADD_HOTZONE,              ///<光栅图添加热区
    REMOTE_NOTIFY_ACTION_MAP_ADD_MAIN,                 ///<光栅图添加主图
    REMOTE_NOTIFY_ACTION_MAP_DELETE_HOTZONE,           ///<光栅图删除热区
    REMOTE_NOTIFY_ACTION_MAP_DELETE_MAIN,              ///<光栅图删除主图
    REMOTE_NOTIFY_ACTION_MAP_RASTER_MODIFY,
    REMOTE_NOTIFY_ACTION_MAP_RASTER_CHANNEL_CHANGE,    ///<光栅点位修改
    
    REMOTE_NOTIFY_ACTION_MESSAGE_ALARM_NEW, ///<AlarmMessageInfo
    REMOTE_NOTIFY_ACTION_MESSAGE_DOOR_NEW, ///<AlarmMessageInfo.doorMessage

    REMOTE_NOTIFY_ACTION_BUSINESS_NOTIFY,   ///<zgyh business notify
    REMOTE_NOTIFY_ACTION_MESSAGE_ALARMPIC_NOTIFY,  ///<报警图片 海外报警图片独立上报
    
    REMOTE_NOTIFY_ACTION_ALARM_COFIRM_NOTIFY,  ///<报警处理回调
    REMOTE_NOTIFY_ACTION_ALARM_COFIRM_NOTIFY_FINISH, ///<一轮报警处理完成
    REMOTE_NOTIFY_ACTION_ADS_RECONNECT,   ///<ADS的重连处理
    REMOTE_NOTIFY_ACTION_ALARM_HANDLE_FROM_OTHERUSER_NOTIFY, ///其他用户处理报警状态通知 同步更新状态
    REMOTE_NOTIFY_ACTION_ALARM_FACEINFO,
    
    REMOTE_NOTIFY_ACTION_ALARM_SUBSCRIBE_STATUS_UPDATE,
    
    REMOTE_NOTIFY_ACTION_MODIFY_CHANNEL,
    REMOTE_NOTIFY_ACTION_MOVE_DEVICE,///<
    
    REMOTE_NOTIFY_ACTION_DELETE_DEVICE,///<
    REMOTE_NOTIFY_CHANNEL_RIGHT_CHANGE,///<
    REMOTE_NOTIFY_ACTION_USER_ROLE_CHANGED,
    REMOTE_NOTIFY_ACTION_ROLE_ORG_CHANGED,
    REMOTE_NOTIFY_ACTION_LOGIC_ORG_CHANGED,
    REMOTE_NOTIFY_ACTION_DELETE_ORG,///<
    REMOTE_NOTIFY_ACTION_MODIFY_ORG,///<
    REMOTE_NOTIFY_ACTION_MODIFY_MEDIAVK,
    REMOTE_NOTIFY_ACTION_USER_RIGHT_CHANGED,
    REMOTE_NOTIFY_ACTION_DELETE_LOGIC_CHANNEL,///<
    REMOTE_NOTIFY_ACTION_ADD_LOGIC_CHANNEL,///<

    REMOTE_NOTIFY_ACTION_DEVICE_PARSER,///<分级加载
    REMOTE_NOTIFY_ACTION_CHANNEL_PARSER,
    
    REMOTE_NOTIFY_ACTION_USER_CHANGE_PASSWORD, ///< 用户密码被修改
    REMOTE_NOTIFY_ACTION_USER_LOCKED,   ///< 用户被锁定
    REMOTE_NOTIFY_ACTION_USER_DELETE,   ///<用户被删除
    REMOTE_NOTIFY_ACTION_USER_LOGIN_TIME_EXPIRE, ///<用户过期
    REMOTE_NOTIFY_ACTION_USER_LICENSE_EXPIRED, ///授权过期
    REMOTE_NOTIFY_ACTION_USER_FORCE_OFFLINE, ///用户强制下线
    REMOTE_NOTIFY_ACTION_USER_REUSE_CHANGED, ///< 用户复用状态变更
    
    REMOTE_NOTIFY_ACTION_DEVICE_LOAD_FINISHED,
    
    // 可视对讲分两种通知：事件通知 和 消息通知
    REMOTE_NOTIFY_ACTION_VT_CALL_EVENT_REGISTER,    ///< 注册CSC
    REMOTE_NOTIFY_ACTION_VT_CALL_EVENT_STOP,        ///< 呼叫挂断
    REMOTE_NOTIFY_ACTION_VT_CALL_EVENT_INVITE,      ///< 来电通知
    REMOTE_NOTIFY_ACTION_VT_CALL_EVENT_CANCEL,      ///< 两种情况下通知：1.客户端未接通前，VTO取消呼叫； 2.或者客户端30秒内未接听
    REMOTE_NOTIFY_ACTION_VT_CALL_EVENT_BYE,         ///< VTO挂断已接通的通话
    REMOTE_NOTIFY_ACTION_VT_CALL_EVENT_RING,        ///< 对端响铃
    REMOTE_NOTIFY_ACTION_VT_CALL_EVENT_BUSY,        ///< 对端忙线
    REMOTE_NOTIFY_ACTION_VT_CALL_MESSAGE_START,     ///< 对端接听
    REMOTE_NOTIFY_ACTION_VT_CALL_SCS_APP_NOTIFY,
    REMOTE_NOTIFY_ACTION_VT_CALL_TRANSEFER,    ///< 呼叫转移
    
    REMOTE_NOTIFY_ACTION_VTSS_ACCESS_CONTROL_MESSAGE,   ///< 可视对讲开门消息通知
    REMOTE_NOTIFY_ACTION_VTSS_ALARM_MESSAGE,            ///< 可视对讲报警消息通知
    REMOTE_NOTIFY_ACTION_VTSS_USER_INFO_CHANGED,        ///< 可视对讲用户信息修改通知（关联设备被删除，用户被删除，用户被冻结，用户密码被重置）
    REMOTE_NOTIFY_ACTION_VTSS_USER_DELETED,             ///< 用户被删除
    REMOTE_NOTIFY_ACTION_VTSS_PASSWORD_RESET,           ///< 用户密码被重置
    REMOTE_NOTIFY_ACTION_VTSS_USER_FREEZE,              ///< 用户被冻结
    REMOTE_NOTIFY_ACTION_VTSS_LOGIN_ON_OTHER_CLIENT,    ///< 用户在其他终端上登录
    REMOTE_NOTIFY_ACTION_ENTRANCEGUARD_BATCHADD_PERSON,
    REMOTE_NOTIFY_ACTION_ENTRANCEGUARD_ADD_PERSON,       ///<门禁模块新增人员
    REMOTE_NOTIFY_ACTION_ENTRANCEGUARD_DELETE_PERSON,       ///<门禁模块删除人员
    REMOTE_NOTIFY_ACTION_ENTRANCEGUARD_UPDATE_PERSON,       ///<门禁模块人员信息更新
    
    REMOTE_NOTIFY_ACTION_ENTRANCEGUARD_ADD_DEPARTMENT,       ///<门禁模块新增部门
    REMOTE_NOTIFY_ACTION_ENTRANCEGUARD_DELETE_DEPARTMENT,       ///<门禁模块删除部门
    REMOTE_NOTIFY_ACTION_ENTRANCEGUARD_DOORSTATUS_CHANGE,     ///<门禁模块开门状态变更
    REMOTE_NOTIFY_ACTION_ENTRANCEGUARD_GLOBAL_DOORSTATUS_CHANGE,  ///<门禁模块全局常开常关状态变更 entranceguard global doorStatus channge
    REMOTE_NOTIFY_ACTION_ENTRANCEGUARD_GLOBAL_DOORCONFIG_CHANGE, ///<门禁模块全局控制通道配置变更 entranceguard global doorConfig channge
    REMOTE_NOTIFY_ACTION_ENTRANCEGUARD_ALWAYS_DOORSTATUS_CHANGE, ///<门禁模块单门的常开常关状态变更
    ///< 电视墙
    REMOTE_NOTIFY_ACTION_TVWALL_ADD,           ///< 新增电视墙
    REMOTE_NOTIFY_ACTION_TVWALL_MODIFY,        ///< 修改电视墙，本修改通知消息权限字段无效，请勿使用
    REMOTE_NOTIFY_ACTION_TVWALL_DELETE,        ///< 删除电视墙
    REMOTE_NOTIFY_ACTION_TVWALL_MODIFY_RIGHT,  ///< 权限电视墙修改
    REMOTE_NOTIFY_ACTION_TVWALL_MODIFY_CONFIG, ///< 电视墙生效修改
    REMOTE_NOTIFY_ACTION_TVWALL_RUN_INFO,      ///<TODO:-电视墙运行信息通知
    REMOTE_NOTIFY_ACTION_TVWALL_NAME_MODIFY,   ///< 电视墙名字修改
    REMOTE_NOTIFY_ACTION_TVWALL_LAYOUT_MODIFY, ///< 电视墙布局修改通知（非平台通知，由本地判断，如果修改则通知上层）
    
    REMOTE_NOTIFY_ACTION_SIGNAL_STATIC,  ///< 信号灯静态数据传输
    REMOTE_NOTIFY_ACTION_SIGNAL_DYNAMIC, ///< 信号灯动态数据传输
    REMOTE_NOTIFY_ACTION_SIGNAL_STATUS, ///< 信号灯在离线状态

    REMOTE_NOTIFY_ACTION_CENTER_ALARM_MSG, ///< 报警中心报警上报
     REMOTE_NOTIFY_ACTION_CENTER_COMMENT_MSG, ///< 报警中心评论上报
    REMOTE_NOTIFY_ACTION_CENTER_ALARM_HANDLE_MSG, ///< 报警中心处理状态上报
    REMOTE_NOTIFY_ACTION_CENTER_ALARM_FACE_MSG,

    REMOTE_NOTIFY_ACTION_SIGNAL_LOCK_SUCCESS, ///< 信号灯相位锁定成功
    REMOTE_NOTIFY_ACTION_SIGNAL_LOCK_FAILED, ///< 信号灯相位锁定失败
    REMOTE_NOTIFY_ACTION_SIGNAL_UNLOCK_SUCCESS, ///< 信号灯相位解锁成功
    REMOTE_NOTIFY_ACTION_SIGNAL_UNLOCK_FAILED, ///< 信号灯相位解锁失败
    REMOTE_NOTIFY_ACTION_SIGNAL_LOCK_PHASE_SUCCESS, ///< 信号灯相位锁定成功
    REMOTE_NOTIFY_ACTION_SIGNAL_LOCK_PHASE_FAILED, ///< 信号灯相位锁定失败
    REMOTE_NOTIFY_ACTION_SIGNAL_UNLOCK_PHASE_SUCCESS, ///< 信号灯相位解锁成功
    REMOTE_NOTIFY_ACTION_SIGNAL_UNLOCK_PHASE_FAILED, ///< 信号灯相位解锁失败
    REMOTE_NOTIFY_ACTION_SIGNAL_CHANGEPLAN_SUCCESS, ///< 信号灯切换计划成功
    REMOTE_NOTIFY_ACTION_SIGNAL_CHANGEPLAN_FAILED, ///< 信号灯切换计划失败
    REMOTE_NOTIFY_ACTION_SIGNAL_SPECIAL_LIST_WUXI, ///< 无锡所特勤任务列表
    // 可视对讲
    REMOTE_NOTIFY_ACTION_VTSS_DEVICE_DELETED,    ///< 设备被删除
    REMOTE_NOTIFY_ACTION_VTSS_DEVICE_OFFLINE,    ///< 设备离线
    REMOTE_NOTIFY_ACTION_VTSS_DEVICE_ONLINE,     ///< 设备在线
    REMOTE_NOTIFY_ACTION_VTSS_CALLLOG_ADD,       ///< 增加通话记录
    REMOTE_NOTIFY_ACTION_VTSS_SIPNUM_CHANGE,     ///< SIP号码变更
    //人脸库
    REMOTE_NOTIFY_ACTION_FACEREPOSITORY_ADD_REPOSITORY,         ///< 人脸库添加
    REMOTE_NOTIFY_ACTION_FACEREPOSITORY_MODIFY_REPOSITORY,      ///< 人脸库修改
    REMOTE_NOTIFY_ACTION_FACEREPOSITORY_DELETE_REPOSITORY,      ///< 人脸库删除
    //人员类型
    REMOTE_NOTIFY_ACTION_FACEREPOSITORY_ADD_PERSONTYPE,
    REMOTE_NOTIFY_ACTION_FACEREPOSITORY_DELETE_PERSONTYPE,
    REMOTE_NOTIFY_ACTION_FACEREPOSITORY_MODIFY_PERSONTYPE,
    //视频分享加载用户
    REMOTE_NOTIFY_ACTION_VIDEOSHARE_LOAD_DEPAERMENT,
    REMOTE_NOTIFY_ACTION_VIDEOSHARE_LOAD_USER,
    REMOTE_NOTIFY_ACTION_VIDEOSHARE_LOAD_FINISHED,
    
    REMOTE_NOTIFY_ACTION_VIDEO_SHARE_ADD,
    REMOTE_NOTIFY_ACTION_VIDEO_SHARE_CANCEL,
    
    //客流统计
    REMOTE_NOTIFY_ACTION_PASSENGERFLOW_RULE_ADD,
    REMOTE_NOTIFY_ACTION_PASSENGERFLOW_RULE_UPDATE,
    REMOTE_NOTIFY_ACTION_PASSENGERFLOW_RULE_DELETE,
    
    REMOTE_NOTIFY_ACTION_OFFLINECALL_SUBSCRIBE_STATUS_UPDATE,
    REMOTE_NOTIFY_ACTION_WEBSOCKET_RECEIVE_MSG,  ///< websocket收到消息

    REMOTE_NOTIFY_ACTION_VISITOR_CONFIG_UPDATE,
    REMOTE_NOTIFY_ACTION_ALARMHOST_STATUS_UPDATE, ///< 报警主机子系统状态更新
    REMOTE_NOTIFY_ACTION_DEFENCEAREA_STATUS_UPDATE,  ///< 报警主机防区状态更新
    REMOTE_NOTIFY_ACTION_ALARMHOST_REFRESH,  ///< 报警主机更新
    REMOTE_NOTIFY_ACTION_USER_DATA_CHANGE,  ///< 用户视图变更
    
    REMOTE_NOTIFY_ACTION_MESSAGE_TASK_NEW,
    REMOTE_NOTIFY_ACTION_MESSAGE_TASK_HANDLE,
    
    REMOTE_NOTIFY_ACTION_MESSAGE_NOTIFICATION_NEW,
    REMOTE_NOTIFY_ACTION_MESSAGE_NOTIFICATION_HANDLE,
    REMOTE_NOTIFY_ACTION_MESSAGE_NOTIFICATION_ALL_HANDLE,
    REMOTE_NOTIFY_ACTION_MESSAGE_ALARM_GPS_UPDATE,
    REMOTE_NOTIFY_ACTION_ALARM_TYPE_CHANGED, ///< 报警类型变更
    REMOTE_NOTIFY_ACTION_USER_CARD_ADD, ///<卡片添加
    REMOTE_NOTIFY_ACTION_USER_CARD_REPLACE, ///<卡号变更
    REMOTE_NOTIFY_ACTION_MESSAGE_ISECURITY_NEW,

} REMOTE_NOTIFY_ACTION;

@protocol WatcherRemoteNotifyProtocol
@required
-(void)watcherRemoteNotifyArrive:(REMOTE_NOTIFY_ACTION)action data:(id)content;
@end

@protocol RemoteNotifyModuleServiceProtocol <NSObject>

#pragma mark--register function to IDHModuleProtocol
-(void)addWathcer:(id<WatcherRemoteNotifyProtocol>)watcher;

#pragma mark--register function to IDHModuleProtocol
-(void)removeWathcer:(id<WatcherRemoteNotifyProtocol>)watcher;

#pragma mark--register function to IDHModuleProtocol
-(void)notify2Watchers:(REMOTE_NOTIFY_ACTION)action data:(id)content;

@end

